changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - feat
    - title: Bugs Fixed 🚨
      labels:
        - Semver-Minor
        - fix
    - title: Other Changes
      labels:
        - "*"
