on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

name: Bump Version and Update Changelog
jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Update package.json version
        run: |
          NEW_VERSION=${GITHUB_REF_NAME}
          echo "Updating version in package.json to $NEW_VERSION"
          pnpm version --no-git-tag-version ${NEW_VERSION#v}

      - name: Update CHANGELOG.md
        run: |
          echo "## ${GITHUB_REF_NAME} - $(date +'%Y-%m-%d')" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0)^..HEAD --pretty=format:"- %s" >> CHANGELOG.md
          echo "\n" >> CHANGELOG.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): bump version to ${NEW_VERSION} and update changelog"
          git push origin HEAD
