name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install release-please
        run: npm install -g release-please

      - name: Create release PR
        id: release_please
        run: release-please github-release \
          --token=${{ secrets.GITHUB_TOKEN }} \
          --repo-url=kittichanr/kittichanr-blog \
          --default-branch=main \
          --release-type=javascript

      - name: Merge release PR
        if: steps.release_please.outputs.release_created == 'true'
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --author app/github-actions --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER --repo ${{ github.repository }} --merge --admin --delete-branch

      - name: Create GitHub release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
